package com.boxingregistration.app.domain

fun getAllClubs(): List<String>
{
    return listOf(
        "Box Club Triebeľ",
        "Športový klub Miko fit-box",
        "Boxing Club - Robotnícka Telovýchovná Jednota Malacky",
        "Alpha Boxing Club MalackyBox Club Stavbár Nitra",
        "Športový Klub Polície Bratislava",
        "Športový Klub Boxu Spartak Komárno",
        "Linka Box - SK Dunajská Lužná",
        "Alex Gym Poprad",
        "Joko Boxing Centrum",
        "Box Klub Spartan Prešov",
        "BC Dubnica",
        "Box Club Patriot Liptovský Mikuláš",
        "Box Club Imopocomex",
        "Box Team Lučenec",
        "Box Club Slovakia Bratislava",
        "Mestský Športový Klub Vranov nad Topľou",
        "Box Club Power Trebišov",
        "Box Club Global Východ",
        "Box Team Legends",
        "Box Club Levice",
        "Rajcsányi Boxing Club Zlaté Klasy",
        "Pöcz Boxing Team Žitný Ostrov",
        "Boxing Club Košice",
        "Košický Box Klub",
        "Tkáč Box Team",
        "Box Club Guerrero Nitra",
        "Unique Fight Club Nitra",
        "Športový Klub Boxu - Michal Franek",
        "1.Bratislavská boxerňa",
        "Boxing Club Veľké Úľany",
        "Boxing Club Veľké Leváre",
        "Boxing Club Veľké Kozmálovce",
        "Boxing Club Galanta",
        "KO Box Club Galanta",
        "BC Tvrdá Päsť Galanta",
        "Shajtar Gym",
        "RK Box",
        "Underground Box Club",
        "Box Club Zemplín Michalovce 1950",
        "Box Club Zemplín Workout Michalovce",
        "Športový Klub Kickboxu a Boxu Banská Bystrica",
        "Bulldog Boxing Club Sereď",
        "Body - Line Boxing Topoľčany",
        "Boxing Club Holíč",
        "ŠK Záhorák",
        "Boxing Club Trnava",
        "Boxing Academy Trnava",
        "Boxerský klub SM",
        "SUP Box Slovakia Púchov",
        "Best Boxing Club",
        "Bojové športy a sebaobrana Rohožník",
        "Telovýchovná Jednota Spilipo Spišská Nová Ves",
        "BC Považan Nové Mesto nad Váhom",
        "Športový klub Boxu JD Stropkov",
        "Mestský Boxerský Klub Giraltovce",
        "Box Sport Žilina",
        "Obecný Boxerský Klub Tomášikovo",
        "Boxing Club Cirok Nitra",
        "Box Klub Aircraft",
        "Box Club Ružinov 821",
        "Telovýchovná Jednota Box Klub Ždaňa",
        "Box Club Kubo",
        "Box Club Royal Galanta",
        "Box Club Zlaté Moravce",
        "Boxing Club SFG",
        "Boxing Club Steel Fist",
        "Budokan Samaria",
        "Centrum zdravia fitness a bojové športy",
        "Drakula Gym",
        "Fight Gym Orava",
        "Fire Gym",
        "Genkikan Box Academy",
        "Gladiators Team Partizánske - Prestige Sport Club",
        "K1 Team Terasa",
        "Pro Box Team Nitra",
        "Škola Boxu Levice",
        "Škola Boxu Nové Zámky",
        "Športová Akadémia Boxu Nitra"
    ).sorted()
}